// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id)
VALUES ($1)
RETURNING id, created_at
`

func (q *Queries) CreateAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, id)
	var i Admin
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins
WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, created_at
FROM admins
WHERE id = $1
`

func (q *Queries) GetAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, created_at
FROM admins
ORDER BY created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type ListAdminsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminsWithUsers = `-- name: ListAdminsWithUsers :many
SELECT a.id, a.created_at, u.username, u.name, u.role
FROM admins a
JOIN users u ON u.id = a.id
ORDER BY a.created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type ListAdminsWithUsersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListAdminsWithUsersRow struct {
	ID        int64            `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Username  pgtype.Text      `db:"username" json:"username"`
	Name      string           `db:"name" json:"name"`
	Role      string           `db:"role" json:"role"`
}

func (q *Queries) ListAdminsWithUsers(ctx context.Context, arg ListAdminsWithUsersParams) ([]ListAdminsWithUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminsWithUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsWithUsersRow
	for rows.Next() {
		var i ListAdminsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
