// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    description,
    is_active
) VALUES (
    $1,
    $2,
    COALESCE($3, TRUE)
)
RETURNING id, name, description, is_active, created_at
`

type CreateCategoryParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	IsActive    interface{} `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description, arg.IsActive)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description, is_active, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, description, is_active, created_at
FROM categories
WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, description, is_active, created_at
FROM categories
WHERE is_active = TRUE
ORDER BY name
LIMIT $2::int
OFFSET $1::int
`

type ListActiveCategoriesParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListActiveCategories(ctx context.Context, arg ListActiveCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, is_active, created_at
FROM categories
ORDER BY name
LIMIT $2::int
OFFSET $1::int
`

type ListCategoriesParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategories = `-- name: SearchCategories :many
SELECT id, name, description, is_active, created_at
FROM categories
WHERE name ILIKE CONCAT('%', $1, '%')
   OR description ILIKE CONCAT('%', $1, '%')
ORDER BY name
LIMIT $3::int
OFFSET $2::int
`

type SearchCategoriesParams struct {
	Query  interface{} `db:"query" json:"query"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, searchCategories, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryActive = `-- name: SetCategoryActive :one
UPDATE categories
SET
    is_active = $1
WHERE id = $2
RETURNING id, name, description, is_active, created_at
`

type SetCategoryActiveParams struct {
	IsActive pgtype.Bool `db:"is_active" json:"is_active"`
	ID       int32       `db:"id" json:"id"`
}

func (q *Queries) SetCategoryActive(ctx context.Context, arg SetCategoryActiveParams) (Category, error) {
	row := q.db.QueryRow(ctx, setCategoryActive, arg.IsActive, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $1,
    description = $2
WHERE id = $3
RETURNING id, name, description, is_active, created_at
`

type UpdateCategoryParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          int32       `db:"id" json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Description, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
