// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: event_media.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEventMedia = `-- name: AddEventMedia :one
INSERT INTO event_media (
    event_id,
    token,
    uploaded_at,
    uploaded_by
) VALUES (
    $1,
    $2,
    COALESCE($3, NOW()),
    $4
)
RETURNING id, event_id, token, uploaded_at, uploaded_by
`

type AddEventMediaParams struct {
	EventID    pgtype.Int4 `db:"event_id" json:"event_id"`
	Token      string      `db:"token" json:"token"`
	UploadedAt interface{} `db:"uploaded_at" json:"uploaded_at"`
	UploadedBy pgtype.Int8 `db:"uploaded_by" json:"uploaded_by"`
}

func (q *Queries) AddEventMedia(ctx context.Context, arg AddEventMediaParams) (EventMedium, error) {
	row := q.db.QueryRow(ctx, addEventMedia,
		arg.EventID,
		arg.Token,
		arg.UploadedAt,
		arg.UploadedBy,
	)
	var i EventMedium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Token,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const deleteEventMedia = `-- name: DeleteEventMedia :exec
DELETE FROM event_media
WHERE id = $1
`

func (q *Queries) DeleteEventMedia(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEventMedia, id)
	return err
}

const deleteEventMediaByEvent = `-- name: DeleteEventMediaByEvent :exec
DELETE FROM event_media
WHERE event_id = $1
`

func (q *Queries) DeleteEventMediaByEvent(ctx context.Context, eventID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteEventMediaByEvent, eventID)
	return err
}

const getEventMediaByID = `-- name: GetEventMediaByID :one
SELECT id, event_id, token, uploaded_at, uploaded_by
FROM event_media
WHERE id = $1
`

func (q *Queries) GetEventMediaByID(ctx context.Context, id int32) (EventMedium, error) {
	row := q.db.QueryRow(ctx, getEventMediaByID, id)
	var i EventMedium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Token,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const getEventMediaByToken = `-- name: GetEventMediaByToken :one
SELECT id, event_id, token, uploaded_at, uploaded_by
FROM event_media
WHERE token = $1
`

func (q *Queries) GetEventMediaByToken(ctx context.Context, token string) (EventMedium, error) {
	row := q.db.QueryRow(ctx, getEventMediaByToken, token)
	var i EventMedium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Token,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const listEventMedia = `-- name: ListEventMedia :many
SELECT id, event_id, token, uploaded_at, uploaded_by
FROM event_media
WHERE event_id = $1
ORDER BY uploaded_at DESC, id DESC
LIMIT $3::int
OFFSET $2::int
`

type ListEventMediaParams struct {
	EventID pgtype.Int4 `db:"event_id" json:"event_id"`
	Offset  int32       `db:"offset" json:"offset"`
	Limit   int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListEventMedia(ctx context.Context, arg ListEventMediaParams) ([]EventMedium, error) {
	rows, err := q.db.Query(ctx, listEventMedia, arg.EventID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMedium
	for rows.Next() {
		var i EventMedium
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Token,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventMediaByUploader = `-- name: ListEventMediaByUploader :many
SELECT id, event_id, token, uploaded_at, uploaded_by
FROM event_media
WHERE uploaded_by = $1
ORDER BY uploaded_at DESC, id DESC
LIMIT $3::int
OFFSET $2::int
`

type ListEventMediaByUploaderParams struct {
	UploadedBy pgtype.Int8 `db:"uploaded_by" json:"uploaded_by"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListEventMediaByUploader(ctx context.Context, arg ListEventMediaByUploaderParams) ([]EventMedium, error) {
	rows, err := q.db.Query(ctx, listEventMediaByUploader, arg.UploadedBy, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMedium
	for rows.Next() {
		var i EventMedium
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Token,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
