// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizer_verification_requests.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizerVerificationRequest = `-- name: CreateOrganizerVerificationRequest :one
INSERT INTO organizer_verification_requests (
    organizer_id,
    status,
    organizer_comment,
    admin_comment,
    reviewed_by,
    reviewed_at
) VALUES (
    $1,
    COALESCE($2, 'pending'),
    $3,
    $4,
    $5,
    $6
)
RETURNING id, organizer_id, status, organizer_comment, admin_comment, reviewed_by, submitted_at, reviewed_at
`

type CreateOrganizerVerificationRequestParams struct {
	OrganizerID      int64            `db:"organizer_id" json:"organizer_id"`
	Status           interface{}      `db:"status" json:"status"`
	OrganizerComment pgtype.Text      `db:"organizer_comment" json:"organizer_comment"`
	AdminComment     pgtype.Text      `db:"admin_comment" json:"admin_comment"`
	ReviewedBy       pgtype.Int8      `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamp `db:"reviewed_at" json:"reviewed_at"`
}

func (q *Queries) CreateOrganizerVerificationRequest(ctx context.Context, arg CreateOrganizerVerificationRequestParams) (OrganizerVerificationRequest, error) {
	row := q.db.QueryRow(ctx, createOrganizerVerificationRequest,
		arg.OrganizerID,
		arg.Status,
		arg.OrganizerComment,
		arg.AdminComment,
		arg.ReviewedBy,
		arg.ReviewedAt,
	)
	var i OrganizerVerificationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.OrganizerComment,
		&i.AdminComment,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getLatestPendingOrganizerVerificationRequest = `-- name: GetLatestPendingOrganizerVerificationRequest :one
SELECT id, organizer_id, status, organizer_comment, admin_comment, reviewed_by, submitted_at, reviewed_at
FROM organizer_verification_requests
WHERE organizer_id = $1
    AND status = 'pending'
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestPendingOrganizerVerificationRequest(ctx context.Context, organizerID int64) (OrganizerVerificationRequest, error) {
	row := q.db.QueryRow(ctx, getLatestPendingOrganizerVerificationRequest, organizerID)
	var i OrganizerVerificationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.OrganizerComment,
		&i.AdminComment,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const listOrganizerVerificationRequests = `-- name: ListOrganizerVerificationRequests :many
SELECT id, organizer_id, status, organizer_comment, admin_comment, reviewed_by, submitted_at, reviewed_at
FROM organizer_verification_requests
WHERE organizer_id = $1
ORDER BY submitted_at DESC, id DESC
LIMIT $3::int
OFFSET $2::int
`

type ListOrganizerVerificationRequestsParams struct {
	OrganizerID int64 `db:"organizer_id" json:"organizer_id"`
	Offset      int32 `db:"offset" json:"offset"`
	Limit       int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListOrganizerVerificationRequests(ctx context.Context, arg ListOrganizerVerificationRequestsParams) ([]OrganizerVerificationRequest, error) {
	rows, err := q.db.Query(ctx, listOrganizerVerificationRequests, arg.OrganizerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizerVerificationRequest
	for rows.Next() {
		var i OrganizerVerificationRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Status,
			&i.OrganizerComment,
			&i.AdminComment,
			&i.ReviewedBy,
			&i.SubmittedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizerVerificationRequestComment = `-- name: UpdateOrganizerVerificationRequestComment :one
UPDATE organizer_verification_requests
SET organizer_comment = $1,
        submitted_at = NOW()
WHERE id = $2
RETURNING id, organizer_id, status, organizer_comment, admin_comment, reviewed_by, submitted_at, reviewed_at
`

type UpdateOrganizerVerificationRequestCommentParams struct {
	OrganizerComment pgtype.Text `db:"organizer_comment" json:"organizer_comment"`
	ID               int32       `db:"id" json:"id"`
}

func (q *Queries) UpdateOrganizerVerificationRequestComment(ctx context.Context, arg UpdateOrganizerVerificationRequestCommentParams) (OrganizerVerificationRequest, error) {
	row := q.db.QueryRow(ctx, updateOrganizerVerificationRequestComment, arg.OrganizerComment, arg.ID)
	var i OrganizerVerificationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Status,
		&i.OrganizerComment,
		&i.AdminComment,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}
