// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizer = `-- name: CreateOrganizer :one
INSERT INTO organizers (
    id,
    organization_name,
    about,
    verified_at,
    verified_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_name, about, verified_at, verified_by, created_at, updated_at
`

type CreateOrganizerParams struct {
	ID               int64            `db:"id" json:"id"`
	OrganizationName string           `db:"organization_name" json:"organization_name"`
	About            pgtype.Text      `db:"about" json:"about"`
	VerifiedAt       pgtype.Timestamp `db:"verified_at" json:"verified_at"`
	VerifiedBy       pgtype.Int8      `db:"verified_by" json:"verified_by"`
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, createOrganizer,
		arg.ID,
		arg.OrganizationName,
		arg.About,
		arg.VerifiedAt,
		arg.VerifiedBy,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganizer = `-- name: DeleteOrganizer :exec
DELETE FROM organizers
WHERE id = $1
`

func (q *Queries) DeleteOrganizer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrganizer, id)
	return err
}

const getOrganizer = `-- name: GetOrganizer :one
SELECT id, organization_name, about, verified_at, verified_by, created_at, updated_at
FROM organizers
WHERE id = $1
`

func (q *Queries) GetOrganizer(ctx context.Context, id int64) (Organizer, error) {
	row := q.db.QueryRow(ctx, getOrganizer, id)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizerWithUser = `-- name: GetOrganizerWithUser :one
SELECT o.id, o.organization_name, o.about, o.verified_at, o.verified_by, o.created_at, o.updated_at, u.username, u.name, u.role, u.state
FROM organizers o
JOIN users u ON u.id = o.id
WHERE o.id = $1
`

type GetOrganizerWithUserRow struct {
	ID               int64            `db:"id" json:"id"`
	OrganizationName string           `db:"organization_name" json:"organization_name"`
	About            pgtype.Text      `db:"about" json:"about"`
	VerifiedAt       pgtype.Timestamp `db:"verified_at" json:"verified_at"`
	VerifiedBy       pgtype.Int8      `db:"verified_by" json:"verified_by"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Username         pgtype.Text      `db:"username" json:"username"`
	Name             string           `db:"name" json:"name"`
	Role             string           `db:"role" json:"role"`
	State            string           `db:"state" json:"state"`
}

func (q *Queries) GetOrganizerWithUser(ctx context.Context, id int64) (GetOrganizerWithUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerWithUser, id)
	var i GetOrganizerWithUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Name,
		&i.Role,
		&i.State,
	)
	return i, err
}

const listOrganizers = `-- name: ListOrganizers :many
SELECT id, organization_name, about, verified_at, verified_by, created_at, updated_at
FROM organizers
ORDER BY created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type ListOrganizersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListOrganizers(ctx context.Context, arg ListOrganizersParams) ([]Organizer, error) {
	rows, err := q.db.Query(ctx, listOrganizers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organizer
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.About,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnverifiedOrganizers = `-- name: ListUnverifiedOrganizers :many
SELECT id, organization_name, about, verified_at, verified_by, created_at, updated_at
FROM organizers
WHERE verified_at IS NULL
ORDER BY created_at ASC
LIMIT $2::int
OFFSET $1::int
`

type ListUnverifiedOrganizersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListUnverifiedOrganizers(ctx context.Context, arg ListUnverifiedOrganizersParams) ([]Organizer, error) {
	rows, err := q.db.Query(ctx, listUnverifiedOrganizers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organizer
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.About,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedOrganizers = `-- name: ListVerifiedOrganizers :many
SELECT id, organization_name, about, verified_at, verified_by, created_at, updated_at
FROM organizers
WHERE verified_at IS NOT NULL
ORDER BY verified_at DESC
LIMIT $2::int
OFFSET $1::int
`

type ListVerifiedOrganizersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListVerifiedOrganizers(ctx context.Context, arg ListVerifiedOrganizersParams) ([]Organizer, error) {
	rows, err := q.db.Query(ctx, listVerifiedOrganizers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organizer
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.About,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizerVerification = `-- name: SetOrganizerVerification :one
UPDATE organizers
SET
    verified_at = $1,
    verified_by = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, organization_name, about, verified_at, verified_by, created_at, updated_at
`

type SetOrganizerVerificationParams struct {
	VerifiedAt pgtype.Timestamp `db:"verified_at" json:"verified_at"`
	VerifiedBy pgtype.Int8      `db:"verified_by" json:"verified_by"`
	ID         int64            `db:"id" json:"id"`
}

func (q *Queries) SetOrganizerVerification(ctx context.Context, arg SetOrganizerVerificationParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, setOrganizerVerification, arg.VerifiedAt, arg.VerifiedBy, arg.ID)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizerProfile = `-- name: UpdateOrganizerProfile :one
UPDATE organizers
SET
    organization_name = $1,
    about = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, organization_name, about, verified_at, verified_by, created_at, updated_at
`

type UpdateOrganizerProfileParams struct {
	OrganizationName string      `db:"organization_name" json:"organization_name"`
	About            pgtype.Text `db:"about" json:"about"`
	ID               int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateOrganizerProfile(ctx context.Context, arg UpdateOrganizerProfileParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, updateOrganizerProfile, arg.OrganizationName, arg.About, arg.ID)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizer = `-- name: UpsertOrganizer :one
INSERT INTO organizers (
    id,
    organization_name,
    about,
    verified_at,
    verified_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (id) DO UPDATE
SET
    organization_name = EXCLUDED.organization_name,
    about = EXCLUDED.about,
    verified_at = EXCLUDED.verified_at,
    verified_by = EXCLUDED.verified_by,
    updated_at = NOW()
RETURNING id, organization_name, about, verified_at, verified_by, created_at, updated_at
`

type UpsertOrganizerParams struct {
	ID               int64            `db:"id" json:"id"`
	OrganizationName string           `db:"organization_name" json:"organization_name"`
	About            pgtype.Text      `db:"about" json:"about"`
	VerifiedAt       pgtype.Timestamp `db:"verified_at" json:"verified_at"`
	VerifiedBy       pgtype.Int8      `db:"verified_by" json:"verified_by"`
}

func (q *Queries) UpsertOrganizer(ctx context.Context, arg UpsertOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, upsertOrganizer,
		arg.ID,
		arg.OrganizationName,
		arg.About,
		arg.VerifiedAt,
		arg.VerifiedBy,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.OrganizationName,
		&i.About,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
