// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEventMedia(ctx context.Context, arg AddEventMediaParams) (EventMedium, error)
	AddEventParticipant(ctx context.Context, arg AddEventParticipantParams) (EventParticipant, error)
	BlockUser(ctx context.Context, id int64) error
	CancelEvent(ctx context.Context, arg CancelEventParams) (Event, error)
	CompleteEvent(ctx context.Context, id int32) (Event, error)
	CountAvailableEventsForVolunteer(ctx context.Context, volunteerID pgtype.Int8) (int64, error)
	CountEvents(ctx context.Context) (int64, error)
	CountParticipantsForEvent(ctx context.Context, eventID pgtype.Int4) (int64, error)
	CreateAdmin(ctx context.Context, id int64) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error)
	CreateOrganizerVerificationRequest(ctx context.Context, arg CreateOrganizerVerificationRequestParams) (OrganizerVerificationRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVolunteer(ctx context.Context, arg CreateVolunteerParams) (Volunteer, error)
	CreateVolunteerApplication(ctx context.Context, arg CreateVolunteerApplicationParams) (VolunteerApplication, error)
	DeleteAdmin(ctx context.Context, id int64) error
	DeleteEvent(ctx context.Context, id int32) error
	DeleteEventMedia(ctx context.Context, id int32) error
	DeleteEventMediaByEvent(ctx context.Context, eventID pgtype.Int4) error
	DeleteOrganizer(ctx context.Context, id int64) error
	DeleteParticipantsByEvent(ctx context.Context, eventID pgtype.Int4) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVolunteer(ctx context.Context, id int64) error
	DeleteVolunteerApplication(ctx context.Context, id int32) error
	GetAdmin(ctx context.Context, id int64) (Admin, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetEventByID(ctx context.Context, id int32) (Event, error)
	GetEventMediaByID(ctx context.Context, id int32) (EventMedium, error)
	GetEventMediaByToken(ctx context.Context, token string) (EventMedium, error)
	GetEventParticipant(ctx context.Context, arg GetEventParticipantParams) (EventParticipant, error)
	GetEventWithOrganizer(ctx context.Context, id int32) (GetEventWithOrganizerRow, error)
	GetLatestPendingOrganizerVerificationRequest(ctx context.Context, organizerID int64) (OrganizerVerificationRequest, error)
	GetOrganizer(ctx context.Context, id int64) (Organizer, error)
	GetOrganizerWithUser(ctx context.Context, id int64) (GetOrganizerWithUserRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	GetVolunteer(ctx context.Context, id int64) (Volunteer, error)
	GetVolunteerApplication(ctx context.Context, arg GetVolunteerApplicationParams) (VolunteerApplication, error)
	GetVolunteerApplicationByID(ctx context.Context, id int32) (VolunteerApplication, error)
	GetVolunteerWithUser(ctx context.Context, id int64) (GetVolunteerWithUserRow, error)
	IncrementEventVolunteers(ctx context.Context, arg IncrementEventVolunteersParams) (pgtype.Int4, error)
	ListActiveCategories(ctx context.Context, arg ListActiveCategoriesParams) ([]Category, error)
	ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error)
	ListAdminsWithUsers(ctx context.Context, arg ListAdminsWithUsersParams) ([]ListAdminsWithUsersRow, error)
	ListApplicationsByEvent(ctx context.Context, arg ListApplicationsByEventParams) ([]VolunteerApplication, error)
	ListApplicationsByStatus(ctx context.Context, arg ListApplicationsByStatusParams) ([]VolunteerApplication, error)
	ListApplicationsByVolunteer(ctx context.Context, arg ListApplicationsByVolunteerParams) ([]VolunteerApplication, error)
	ListApplicationsForOrganizer(ctx context.Context, arg ListApplicationsForOrganizerParams) ([]VolunteerApplication, error)
	ListAvailableEventsForVolunteer(ctx context.Context, arg ListAvailableEventsForVolunteerParams) ([]Event, error)
	ListBlockedUsers(ctx context.Context, arg ListBlockedUsersParams) ([]User, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListEventMedia(ctx context.Context, arg ListEventMediaParams) ([]EventMedium, error)
	ListEventMediaByUploader(ctx context.Context, arg ListEventMediaByUploaderParams) ([]EventMedium, error)
	ListEventParticipants(ctx context.Context, arg ListEventParticipantsParams) ([]EventParticipant, error)
	ListEventParticipantsWithUsers(ctx context.Context, arg ListEventParticipantsWithUsersParams) ([]ListEventParticipantsWithUsersRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsByCategory(ctx context.Context, arg ListEventsByCategoryParams) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, arg ListEventsByOrganizerParams) ([]Event, error)
	ListEventsByStatus(ctx context.Context, arg ListEventsByStatusParams) ([]Event, error)
	ListEventsForMap(ctx context.Context, arg ListEventsForMapParams) ([]ListEventsForMapRow, error)
	ListEventsForMapByVolunteer(ctx context.Context, arg ListEventsForMapByVolunteerParams) ([]ListEventsForMapByVolunteerRow, error)
	ListEventsForVolunteer(ctx context.Context, arg ListEventsForVolunteerParams) ([]Event, error)
	ListEventsNearLocation(ctx context.Context, arg ListEventsNearLocationParams) ([]Event, error)
	ListEventsWithPendingApplications(ctx context.Context, arg ListEventsWithPendingApplicationsParams) ([]Event, error)
	ListOrganizerVerificationRequests(ctx context.Context, arg ListOrganizerVerificationRequestsParams) ([]OrganizerVerificationRequest, error)
	ListOrganizers(ctx context.Context, arg ListOrganizersParams) ([]Organizer, error)
	ListOrganizersByStatus(ctx context.Context, arg ListOrganizersByStatusParams) ([]Organizer, error)
	ListParticipantEvents(ctx context.Context, arg ListParticipantEventsParams) ([]EventParticipant, error)
	ListPendingApplicationsByEvent(ctx context.Context, arg ListPendingApplicationsByEventParams) ([]VolunteerApplication, error)
	ListPendingOrganizersWithUsers(ctx context.Context, arg ListPendingOrganizersWithUsersParams) ([]ListPendingOrganizersWithUsersRow, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error)
	ListUsersByIDs(ctx context.Context, ids []int64) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	ListUsersByState(ctx context.Context, arg ListUsersByStateParams) ([]User, error)
	ListUsersNearLocation(ctx context.Context, arg ListUsersNearLocationParams) ([]User, error)
	ListVolunteers(ctx context.Context, arg ListVolunteersParams) ([]Volunteer, error)
	ListVolunteersByCategory(ctx context.Context, arg ListVolunteersByCategoryParams) ([]Volunteer, error)
	ListVolunteersByCategoryWithUsers(ctx context.Context, arg ListVolunteersByCategoryWithUsersParams) ([]ListVolunteersByCategoryWithUsersRow, error)
	ListVolunteersByIDs(ctx context.Context, ids []int64) ([]Volunteer, error)
	ListVolunteersNearLocation(ctx context.Context, arg ListVolunteersNearLocationParams) ([]ListVolunteersNearLocationRow, error)
	ListVolunteersWithUsers(ctx context.Context, arg ListVolunteersWithUsersParams) ([]ListVolunteersWithUsersRow, error)
	RemoveEventParticipant(ctx context.Context, arg RemoveEventParticipantParams) error
	ResetVolunteerApplicationReview(ctx context.Context, id int32) (VolunteerApplication, error)
	SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetCategoryActive(ctx context.Context, arg SetCategoryActiveParams) (Category, error)
	SetEventVolunteerCounts(ctx context.Context, arg SetEventVolunteerCountsParams) (SetEventVolunteerCountsRow, error)
	SetOrganizerVerification(ctx context.Context, arg SetOrganizerVerificationParams) (Organizer, error)
	UnblockUser(ctx context.Context, id int64) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error)
	UpdateOrganizerProfile(ctx context.Context, arg UpdateOrganizerProfileParams) (Organizer, error)
	UpdateOrganizerVerificationRequestComment(ctx context.Context, arg UpdateOrganizerVerificationRequestCommentParams) (OrganizerVerificationRequest, error)
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserState(ctx context.Context, arg UpdateUserStateParams) (User, error)
	UpdateVolunteerApplicationStatus(ctx context.Context, arg UpdateVolunteerApplicationStatusParams) (VolunteerApplication, error)
	UpdateVolunteerCategories(ctx context.Context, arg UpdateVolunteerCategoriesParams) (Volunteer, error)
	UpdateVolunteerProfile(ctx context.Context, arg UpdateVolunteerProfileParams) (Volunteer, error)
	UpsertOrganizer(ctx context.Context, arg UpsertOrganizerParams) (Organizer, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UpsertVolunteer(ctx context.Context, arg UpsertVolunteerParams) (Volunteer, error)
	UpsertVolunteerApplication(ctx context.Context, arg UpsertVolunteerApplicationParams) (VolunteerApplication, error)
}

var _ Querier = (*Queries)(nil)
